easy_admin:
    site_name: 'Symfony-base EasyAdmin'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
        menu:
            - { label: 'Start', default: true, icon: 'tools', route: 'easyadmin_home' }
            - { label: 'Users', entity: 'User', icon: 'users' }
            - { label: 'Back to home', icon: 'home', route: 'home' }
    entities:
        User:
            class: App\Entity\User
            role: ROLE_ADMIN
            list:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - roles
                sort: [username, ASC]
                actions:
                    - { name: loginAs, label: 'Login as' }
            edit:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'plainPassword', type: 'password', type_options: { required: false } }
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              'ROLE_USER': 'ROLE_USER'
                              'ROLE_ADMIN': 'ROLE_ADMIN'
                              'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN'
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - username
                    - email
                    - { property: enabled, type_options: { data: true } }
                    - lastLogin
                    - { property: 'plainPassword', type: 'password', type_options: { required: true } }
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              'ROLE_USER': 'ROLE_USER'
                              'ROLE_ADMIN': 'ROLE_ADMIN'
                              'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN'
                form_options: { validation_groups: ['Registration'] }
